export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";
export const ADD_NEW_ADMIN = "ADD_NEW_ADMIN";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
