export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const GET_FETCH_SUCCESS = "GET_FETCH_SUCCESS";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_SALES = "ADD_NEW_SALES";
export const ADD_NEW_USERS = "ADD_NEW_USERS";

export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
